a=int(input("Enter first number: "))
b=int(input("Enter second number: "))
print("sum of two numbers:",a+b)
print("difference of two numbers:",a-b)
print("product of two numbers:",a*b)
print("division of two numbers:",a/b)
